---
# Variable setup.
- name: Install lsb-release
  apt:
    name: lsb-release
    state: present

- name: Add an Apt signing key, uses whichever key is at the URL
  get_url:
    url: https://packages.redis.io/gpg
    dest: /etc/apt/trusted.gpg.d/redis-archive-keyring.gpg
    mode: 0644
    force: true

- name: Adding Redis repository
  template:
    src: redis_repo.j2
    dest: /etc/apt/sources.list.d/redis.list

- name: Updating OS
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install Redis
  apt:
    name: redis
    state: present
  notify:
    - restart redis
