# docker ansible_host=3.86.197.101 ansible_user=ubuntu ansible_ssh_private_key_file=./key/blaize-test.pem owner=docker
mongodb ansible_host=192.168.22.12 ansible_user=vagrant ansible_ssh_private_key_file=./key/local.pem owner=mongodb
# redis ansible_host=3.85.221.20 ansible_user=ubuntu ansible_ssh_private_key_file=./key/blaize-test.pem owner=redis
