docker ansible_host=192.168.22.12 ansible_user=vagrant ansible_ssh_private_key_file=./key/local.pem.pem owner=docker
# mongodb ansible_host=192.168.22.12 ansible_user=vagrant ansible_ssh_private_key_file=./key/local.pem owner=mongodb
# redis ansible_host=192.168.22.12 ansible_user=vagrant ansible_ssh_private_key_file=./key/local.pem owner=redis
