docker ansible_host=44.210.145.189 ansible_user=ubuntu ansible_ssh_private_key_file=./key/hillel-test.pem owner=docker
mongodb ansible_host=3.92.215.184 ansible_user=ec2-user ansible_ssh_private_key_file=./key/hillel-test.pem owner=mongodb
redis ansible_host=3.92.215.184 ansible_user=ec2-user ansible_ssh_private_key_file=./key/hillel-test.pem owner=redis