---
- name: Adding MongoDB service file
  template:
    src: mongo_servicefile.j2
    dest: /usr/lib/systemd/system/mongod.service
    owner: root
    group: root
    mode: 0777
    force: yes
  notify:
    - daemon_reload

- name: Creating Log directory
  file:
    state: directory
    path: "{{ item }}"
    owner: mongod
    group: mongod
    mode: 0755
  loop:
    - /data
    - /data/log
    - /data/log/mongodb
    - /data/db
    - /var/run/mongodb/

- name: Adding MongoDB initialization config file
  template:
    src: mongo_init_config.j2
    dest: /etc/mongod.conf
    mode: 0644
    force: yes

- name: Restart mongod service
  service:
     name: mongod
     state: restarted