---
- name: Add an Apt signing key, uses whichever key is at the URL
  get_url:
    url: https://www.mongodb.org/static/pgp/server-6.0.asc
    dest: /etc/apt/trusted.gpg.d/mongodb.asc
    mode: 0644
    force: true

- name: Adding MongoDB repository
  template:
    src: mongo_repo.j2
    dest: /etc/apt/sources.list.d/mongodb-org-6.0.list

- name: Updating OS
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Installing MongoDB package
  apt:
    name: "{{ mongo_package }}"
    state: present

- name: Daemon Reload
  shell: systemctl daemon-reload

- name: Starting MongoDB service
  service:
    name: mongod
    state: started

- name: Enable MongoDB service
  service:
    name: mongod
    enabled: yes
